apiVersion: console.openshift.io/v1alpha5
kind: Assistant
metadata:
  name: assistant-config
spec:
  {{- if .Values.hideAdvancedTab }}
  hideAdvancedTab: {{ .Values.hideAdvancedTab }}
  {{- end }}
  backends:
{{ toYaml .Values.backends | indent 4 }}
