apiVersion: v1
kind: Secret
metadata:
  name: wisdom-for-rhassistant-secret
stringData:
  wisdom-email: 'Harikrishnan.Balagopal@ibm.com'
  wisdom-token: 'sk-8678c137a1581b4c8df5b139967b5845f06af95086bd717e'
